export * from './auth/auth.routes';
export * from './user/user.routes';
export * from './channel/channel.routes';
export * from './swagger/swagger.routes';
export * from './post/post.routes';
export * from './subscription/subscription.routes';
export * from './like/like.routes';
export * from './comment/comment.routes';
export * from './message/message.routes';
